// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: albums.proto

package my_albums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_albums_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{0}
}

type GetByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_albums_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{1}
}

func (x *GetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Album struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title  string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist string  `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Price  float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Album) Reset() {
	*x = Album{}
	if protoimpl.UnsafeEnabled {
		mi := &file_albums_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{2}
}

func (x *Album) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Album) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Album) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Album) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type MyAlbums struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Albums []*Album `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`
}

func (x *MyAlbums) Reset() {
	*x = MyAlbums{}
	if protoimpl.UnsafeEnabled {
		mi := &file_albums_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyAlbums) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyAlbums) ProtoMessage() {}

func (x *MyAlbums) ProtoReflect() protoreflect.Message {
	mi := &file_albums_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyAlbums.ProtoReflect.Descriptor instead.
func (*MyAlbums) Descriptor() ([]byte, []int) {
	return file_albums_proto_rawDescGZIP(), []int{3}
}

func (x *MyAlbums) GetAlbums() []*Album {
	if x != nil {
		return x.Albums
	}
	return nil
}

var File_albums_proto protoreflect.FileDescriptor

var file_albums_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x6d, 0x79, 0x5f, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5b, 0x0a, 0x05, 0x41,
	0x6c, 0x62, 0x75, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x34, 0x0a, 0x08, 0x4d, 0x79, 0x41, 0x6c,
	0x62, 0x75, 0x6d, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x79, 0x5f, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73,
	0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x06, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x32, 0xaf,
	0x02, 0x0a, 0x0c, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x12, 0x17, 0x2e, 0x6d,
	0x79, 0x5f, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x79, 0x5f, 0x61, 0x6c, 0x62, 0x75, 0x6d,
	0x73, 0x2e, 0x4d, 0x79, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x42, 0x79, 0x49, 0x44, 0x12, 0x19, 0x2e, 0x6d,
	0x79, 0x5f, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6d, 0x79, 0x5f, 0x61, 0x6c, 0x62,
	0x75, 0x6d, 0x73, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x08, 0x41,
	0x64, 0x64, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x10, 0x2e, 0x6d, 0x79, 0x5f, 0x61, 0x6c, 0x62,
	0x75, 0x6d, 0x73, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x1a, 0x13, 0x2e, 0x6d, 0x79, 0x5f, 0x61,
	0x6c, 0x62, 0x75, 0x6d, 0x73, 0x2e, 0x4d, 0x79, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x22, 0x00,
	0x12, 0x36, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x12,
	0x10, 0x2e, 0x6d, 0x79, 0x5f, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x2e, 0x41, 0x6c, 0x62, 0x75,
	0x6d, 0x1a, 0x13, 0x2e, 0x6d, 0x79, 0x5f, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x2e, 0x4d, 0x79,
	0x41, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x10, 0x2e, 0x6d, 0x79, 0x5f, 0x61, 0x6c, 0x62,
	0x75, 0x6d, 0x73, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x1a, 0x13, 0x2e, 0x6d, 0x79, 0x5f, 0x61,
	0x6c, 0x62, 0x75, 0x6d, 0x73, 0x2e, 0x4d, 0x79, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x22, 0x00,
	0x42, 0x1a, 0x5a, 0x18, 0x67, 0x6f, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x64, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x2f, 0x6d, 0x79, 0x5f, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_albums_proto_rawDescOnce sync.Once
	file_albums_proto_rawDescData = file_albums_proto_rawDesc
)

func file_albums_proto_rawDescGZIP() []byte {
	file_albums_proto_rawDescOnce.Do(func() {
		file_albums_proto_rawDescData = protoimpl.X.CompressGZIP(file_albums_proto_rawDescData)
	})
	return file_albums_proto_rawDescData
}

var file_albums_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_albums_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil),   // 0: my_albums.EmptyRequest
	(*GetByIDRequest)(nil), // 1: my_albums.GetByIDRequest
	(*Album)(nil),          // 2: my_albums.Album
	(*MyAlbums)(nil),       // 3: my_albums.MyAlbums
}
var file_albums_proto_depIdxs = []int32{
	2, // 0: my_albums.MyAlbums.albums:type_name -> my_albums.Album
	0, // 1: my_albums.AlbumService.GetAlbums:input_type -> my_albums.EmptyRequest
	1, // 2: my_albums.AlbumService.GetAlbumByID:input_type -> my_albums.GetByIDRequest
	2, // 3: my_albums.AlbumService.AddAlbum:input_type -> my_albums.Album
	2, // 4: my_albums.AlbumService.UpdateAlbum:input_type -> my_albums.Album
	2, // 5: my_albums.AlbumService.DeleteAlbum:input_type -> my_albums.Album
	3, // 6: my_albums.AlbumService.GetAlbums:output_type -> my_albums.MyAlbums
	2, // 7: my_albums.AlbumService.GetAlbumByID:output_type -> my_albums.Album
	3, // 8: my_albums.AlbumService.AddAlbum:output_type -> my_albums.MyAlbums
	3, // 9: my_albums.AlbumService.UpdateAlbum:output_type -> my_albums.MyAlbums
	3, // 10: my_albums.AlbumService.DeleteAlbum:output_type -> my_albums.MyAlbums
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_albums_proto_init() }
func file_albums_proto_init() {
	if File_albums_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_albums_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_albums_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_albums_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Album); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_albums_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyAlbums); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_albums_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_albums_proto_goTypes,
		DependencyIndexes: file_albums_proto_depIdxs,
		MessageInfos:      file_albums_proto_msgTypes,
	}.Build()
	File_albums_proto = out.File
	file_albums_proto_rawDesc = nil
	file_albums_proto_goTypes = nil
	file_albums_proto_depIdxs = nil
}
